### ISSUE TITLE
extract runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Fank** [nicksnyder/go-i18n#213]
When trying to run `goi18n extract` i get following:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5dd09d]

goroutine 1 [running]:
main.extractStringLiteral(0x6a38c0, 0xc000206fa0, 0x0, 0x0, 0xc0001a8c38)
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/extract_command.go:262 +0x5d
main.(*extractor).extractMessage(0xc00023d6e0, 0xc0001ffdc0)
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/extract_command.go:222 +0x29f
main.(*extractor).extractMessages(0xc00023d6e0, 0x6a0d40, 0xc0001ffdc0)
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/extract_command.go:154 +0x28f
main.(*extractor).Visit(0xc00023d6e0, 0x6a0d40, 0xc0001ffdc0, 0x5dc7cf, 0xc00023d6e0)
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/extract_command.go:140 +0x3f
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0d40, 0xc0001ffdc0)
        /usr/local/go/src/go/ast/walk.go:52 +0x66
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a16c0, 0xc000206fc0)
        /usr/local/go/src/go/ast/walk.go:143 +0x15da
go/ast.walkExprList(0x69fae0, 0xc00023d6e0, 0xc000204550, 0x1, 0x1)
        /usr/local/go/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0bc0, 0xc0001ffe00)
        /usr/local/go/src/go/ast/walk.go:137 +0x1096
go/ast.walkExprList(0x69fae0, 0xc00023d6e0, 0xc000204560, 0x1, 0x1)
        /usr/local/go/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a09c0, 0xc0001ffe40)
        /usr/local/go/src/go/ast/walk.go:207 +0x214f
go/ast.walkStmtList(0x69fae0, 0xc00023d6e0, 0xc000207060, 0x2, 0x2)
        /usr/local/go/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0b40, 0xc000203110)
        /usr/local/go/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a1140, 0xc000208040)
        /usr/local/go/src/go/ast/walk.go:231 +0x1c7c
go/ast.walkStmtList(0x69fae0, 0xc00023d6e0, 0xc000204710, 0x1, 0x1)
        /usr/local/go/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0b40, 0xc0002033b0)
        /usr/local/go/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a1140, 0xc000208100)
        /usr/local/go/src/go/ast/walk.go:231 +0x1c7c
go/ast.walkStmtList(0x69fae0, 0xc00023d6e0, 0xc0001e0900, 0x5, 0x8)
        /usr/local/go/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0b40, 0xc0002035f0)
        /usr/local/go/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a13c0, 0xc0001fbe00)
        /usr/local/go/src/go/ast/walk.go:285 +0x2946
go/ast.walkStmtList(0x69fae0, 0xc00023d6e0, 0xc000447200, 0x11, 0x20)
        /usr/local/go/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0b40, 0xc0002038f0)
        /usr/local/go/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a1000, 0xc000204a30)
        /usr/local/go/src/go/ast/walk.go:98 +0x2c1c
go/ast.walkExprList(0x69fae0, 0xc00023d6e0, 0xc000204a40, 0x1, 0x1)
        /usr/local/go/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0bc0, 0xc000208600)
        /usr/local/go/src/go/ast/walk.go:137 +0x1096
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0e80, 0xc000204a60)
        /usr/local/go/src/go/ast/walk.go:196 +0x1b78
go/ast.walkStmtList(0x69fae0, 0xc00023d6e0, 0xc000204a70, 0x1, 0x1)
        /usr/local/go/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0b40, 0xc000203920)
        /usr/local/go/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a1140, 0xc000209340)
        /usr/local/go/src/go/ast/walk.go:231 +0x1c7c
go/ast.walkStmtList(0x69fae0, 0xc00023d6e0, 0xc00020d940, 0x2, 0x2)
        /usr/local/go/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0b40, 0xc000210810)
        /usr/local/go/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a13c0, 0xc00020e370)
        /usr/local/go/src/go/ast/walk.go:285 +0x2946
go/ast.walkStmtList(0x69fae0, 0xc00023d6e0, 0xc000205310, 0x1, 0x1)
        /usr/local/go/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0b40, 0xc000210840)
        /usr/local/go/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a1140, 0xc000209380)
        /usr/local/go/src/go/ast/walk.go:231 +0x1c7c
go/ast.walkStmtList(0x69fae0, 0xc00023d6e0, 0xc000471d00, 0x10, 0x10)
        /usr/local/go/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0b40, 0xc000210a50)
        /usr/local/go/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0fc0, 0xc000210a80)
        /usr/local/go/src/go/ast/walk.go:344 +0xd98
go/ast.walkDeclList(0x69fae0, 0xc00023d6e0, 0xc000181000, 0x28, 0x40)
        /usr/local/go/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0x69fae0, 0xc00023d6e0, 0x6a0f40, 0xc0001e1200)
        /usr/local/go/src/go/ast/walk.go:353 +0x264e
main.extractMessages(0xc0001d8000, 0x7b35, 0x7d35, 0x7b35, 0x7d35, 0x0, 0x0, 0x4a0ec6)
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/extract_command.go:126 +0x13d
main.(*extractCommand).execute.func1(0xc000016a50, 0x21, 0x6a51e0, 0xc000459040, 0x0, 0x0, 0x4bf3af, 0xc000459040)
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/extract_command.go:95 +0x138
path/filepath.walk(0xc000016a50, 0x21, 0x6a51e0, 0xc000459040, 0xc0001abd50, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:360 +0x425
path/filepath.walk(0xc000407985, 0xb, 0x6a51e0, 0xc00042a410, 0xc0001abd50, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:384 +0x2ff
path/filepath.walk(0xc0000145b5, 0x3, 0x6a51e0, 0xc000093110, 0xc0001abd50, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:384 +0x2ff
path/filepath.walk(0x64f174, 0x1, 0x6a51e0, 0xc000092d00, 0xc0001abd50, 0x0, 0x10)
        /usr/local/go/src/path/filepath/path.go:384 +0x2ff
path/filepath.Walk(0x64f174, 0x1, 0xc000071d50, 0xc0000a8240, 0x40)
        /usr/local/go/src/path/filepath/path.go:406 +0xff
main.(*extractCommand).execute(0xc00008c280, 0xc00000c090, 0x0)
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/extract_command.go:75 +0x363
main.testableMain(0xc00000c090, 0x1, 0x1, 0xc00008e058)
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/main.go:123 +0x3e2
main.main()
        /home/fank/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.0.3/goi18n/main.go:96 +0x64
```

**Comment by nicksnyder** [comment]
fixed in https://github.com/nicksnyder/go-i18n/pull/212
