### ISSUE TITLE
How to translate strings with template syntax?

### ISSUE THREAD

**Issue by misitebao** [nicksnyder/go-i18n#275]
The requirement is to return different template strings according to different languages, but not to parse the template.

```toml
# en.toml
Name = """
My name is {{ .Name}}.
"""
```

```toml
# zh.toml
Name = """
我的名字是 {{ .Name}}。
"""
```

Want to return different strings based on different languages, e.g. `My name is {{ .Name}}.` or `我的名字是 {{ .Name}}。`

**Comment by misitebao** [comment]
@nicksnyder 
What do you think about this issue?

**Comment by nicksnyder** [comment]
What is your use case for this?

Would it work to export the `getMessageTemplate` on the `Bundle` struct?

https://github.com/nicksnyder/go-i18n/blob/57bd175f4eca85b370ebc664ec389a6c40d89d81/v2/i18n/bundle.go#L138-L144

**Comment by misitebao** [comment]
I want to translate a string with template syntax, but using the example according to the documentation, it gives an error:

```toml
# en.toml
HelpTemplate = """
{{with (or .Long .Short)}}{{. | trimTrailingWhitespaces}}{{end}}

Usag:{{if .Runnable}}
  {{.UseLine}}{{end}}{{if .HasAvailableSubCommands}}{{end}} {{if gt (len .Aliases) 0}}

Aliases:
  {{.NameAndAliases}}{{end}}{{if .HasExample}}

Examples:
{{.Example}}{{end}}{{if .HasAvailableSubCommands}}

Available Commands:{{range .Commands}}{{if (or .IsAvailableCommand)}}
  {{rpad .Name .NamePadding }} {{.Short}}{{end}}{{end}}{{end}}{{if .HasAvailableLocalFlags}}

Flags:
{{.LocalFlags.FlagUsages | trimTrailingWhitespaces}}{{end}}{{if .HasAvailableInheritedFlags}}

Global Flags:
{{.InheritedFlags.FlagUsages | trimTrailingWhitespaces}}{{end}}{{if .HasHelpSubCommands}}

Additional help topics:{{range .Commands}}{{if .IsAdditionalHelpTopicCommand}}
  {{rpad .CommandPath .CommandPathPadding}} {{.Short}}{{end}}{{end}}{{end}}{{if .HasAvailableSubCommands}}

Use "{{.CommandPath}} [command] --help" for more information about a command.{{end}}

"""
```

```toml
# zh-Hans.toml
HelpTemplate = """
{{with (or .Long .Short)}}{{. | trimTrailingWhitespaces}}{{end}}

使用方法:{{if .Runnable}}
  {{.UseLine}}{{end}}{{if .HasAvailableSubCommands}}{{end}} {{if gt (len .Aliases) 0}}

别名:
  {{.NameAndAliases}}{{end}}{{if .HasExample}}

Examples:
{{.Example}}{{end}}{{if .HasAvailableSubCommands}}

Available Commands:{{range .Commands}}{{if (or .IsAvailableCommand)}}
  {{rpad .Name .NamePadding }} {{.Short}}{{end}}{{end}}{{end}}{{if .HasAvailableLocalFlags}}

Flags:
{{.LocalFlags.FlagUsages | trimTrailingWhitespaces}}{{end}}{{if .HasAvailableInheritedFlags}}

Global Flags:
{{.InheritedFlags.FlagUsages | trimTrailingWhitespaces}}{{end}}{{if .HasHelpSubCommands}}

Additional help topics:{{range .Commands}}{{if .IsAdditionalHelpTopicCommand}}
  {{rpad .CommandPath .CommandPathPadding}} {{.Short}}{{end}}{{end}}{{end}}{{if .HasAvailableSubCommands}}

Use "{{.CommandPath}} [command] --help" for more information about a command.{{end}}

"""
```

error:

```shell
$ go run ./cmd/yakia/main.go 
panic: template: :1: function "trimTrailingWhitespaces" not defined

goroutine 1 [running]:
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).MustLocalize(0xc000117cf8?, 0x1?) 
        D:/WorkSpace/GoPATH/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.2.0/i18n/localizer.go:211 +0x3a
github.com/misitebao/yakia/cmd/yakia/internal/i18n.T({0xa9d087, 0xc})
        D:/WorkSpace/Git/misitebao/yakia/cmd/yakia/internal/i18n/i18n.go:27 +0xd8    
github.com/misitebao/yakia/cmd/yakia/internal/commands.glob..func1(0xc1d960?, {0xa9b365?, 0x0?, 0x0?})
        D:/WorkSpace/Git/misitebao/yakia/cmd/yakia/internal/commands/commands.go:20 +0x25
github.com/spf13/cobra.(*Command).execute(0xc1d960, {0xc000056220, 0x0, 0x0})        
        D:/WorkSpace/GoPATH/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc1d960)
        D:/WorkSpace/GoPATH/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        D:/WorkSpace/GoPATH/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918     
github.com/misitebao/yakia/cmd/yakia/internal/commands.Execute()
        D:/WorkSpace/Git/misitebao/yakia/cmd/yakia/internal/commands/commands.go:37 +0x25
main.main()
        D:/WorkSpace/Git/misitebao/yakia/cmd/yakia/main.go:8 +0x17
exit status 2
```

**Comment by nicksnyder** [comment]
There are two ways to solve your problem.

First, you can set the `Funcs` field of `LocalizeConfig` so that go-i18n can execute the template correctly: https://github.com/nicksnyder/go-i18n/blob/main/v2/i18n/localizer.go#L70

Second, you probably don't want all this logic to be in a translation string. I would recommend creating multiple smaller strings to translate and then injecting them into the template that has the logic. See example here: https://github.com/nicksnyder/go-i18n/blob/main/v2/example/main.go

**Comment by nicksnyder** [comment]
With 2.4.0 there is now a way to disable template parsing. Check out the [release notes](https://github.com/nicksnyder/go-i18n/releases/tag/v2.4.0) for more info.
